image: python:3.6

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - apt-get update && apt-get install -y --no-install-recommends gfortran 
          - pip install -r requirements.txt
          - pip install .
          - cd ifscube/examples/
          - python cube_fit_gaussian_cfg.py
          - specfit --overwrite -c halpha_gauss.cfg manga_onedspec.fits 
          - cubefit --overwrite -c halpha_cube.cfg ngc3081_cube.fits

          # Temporarily removing this next two lines due to bug in ppxf.
          # - python voronoi_ppxf.py
          # - cubefit --overwrite -c halpha_cube.cfg ngc3081_cube.bin.fits
