name: ifscube_311
channels:
  - http://ssb.stsci.edu/astroconda
  - https://conda.anaconda.org/sherpa
  - defaults
  - conda-forge

dependencies:

  - python=3.11.7
  - fortran-compiler
  - numpy
  - scipy
  - matplotlib
  - astropy
  - tqdm
  - pytest
  - pip
  
  - pip:
      - ppxf
      - vorbin
